# Generated by Django 3.2.4 on 2021-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210717_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
