# Generated by Django 3.2.4 on 2021-07-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_boards_modify_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='boards',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
