# Generated by Django 3.2.4 on 2021-07-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auth',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
