# Generated by Django 3.2.4 on 2021-07-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auth_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='is_staff',
        ),
    ]
