# Generated by Django 3.2.4 on 2021-07-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210716_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='boad_type',
            new_name='board_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='board',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='board.post'),
        ),
    ]
